apiVersion: v1
kind: ServiceAccount
metadata:
  name: patroni
  namespace: myapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patroni
  namespace: myapp
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patroni
  namespace: myapp
subjects:
  - kind: ServiceAccount
    name: patroni
    namespace: myapp
roleRef:
  kind: Role
  name: patroni
  apiGroup: rbac.authorization.k8s.io