apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: myapp
data:
  postgresql.conf: |
    max_connections = 100
    shared_buffers = 128MB
    effective_cache_size = 384MB
    maintenance_work_mem = 32MB
    checkpoint_completion_target = 0.7
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 4
    effective_io_concurrency = 2
    work_mem = 4MB
    min_wal_size = 1GB
    max_wal_size = 2GB
    max_worker_processes = 2
    max_parallel_workers_per_gather = 1
    max_parallel_workers = 2
    password_encryption = scram-sha-256