apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: myapp
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgresql
      port: 5432
    - name: patroni
      port: 8008