apiVersion: v1
kind: Service
metadata:
  name: postgres-write
  namespace: myapp
spec:
  selector:
    app: postgres
    role: master # Spilo/Patroni default label for leader
  ports:
    - port: 5432
      targetPort: 5432