apiVersion: v1
kind: Pod
metadata:
  name: tres-containers-pod
  namespace: ckad-multi-containers
  labels:
    app: jahez-api
spec:
  containers:
  - name: primero
    image: "busybox:1.28"
    command:
    - sh
    - "-c"
    - while true; do sleep 3600; done
    env:
    - name: ORDER
      value: FIRST
  - name: segundo
    image: "nginx:1.17"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
  - name: tercero
    image: "busybox:1.31.1"
    command:
    - sh
    - "-c"
    - while true; do sleep 3600; done
    env:
    - name: ORDER
      value: THIRD